# define pool
# call 3 stages for which templates are already available
# will pass paramters

trigger:
  - dev

pool: default
variables:
  dockerImage: shaikkhajaibrahim/azuredevopsnov23

stages:
  - stage: buildndeploy
    displayName: 'Build and deploy'
    jobs:
      - job: build
        displayName: 'Build Docker Image Job'
        steps:
          - script: |
              docker image build -t $(dockerImage):$(Build.BuildId) ./src/
              docker image push $(dockerImage):$(Build.BuildId)
      - job: terraform
        displayName: 'Ensure infra is created'
        steps:
          - script: |
              cd deploy/tf_azure
              terraform init
              terraform apply -auto-approve
      - job: kubernetes
        displayName: 'Kubernetes deploy'
        steps:
          - script: |
              kubectl apply -f deploy/k8s
              kubectl set image   deploy/nginx-deployment nginx-deployment=$(dockerImage):$(Build.BuildId) -n workshop
              




      